### ISSUE TITLE
Make homepage slider text editable in a widget block

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-laboutique#23]
The homepage slider images are editable in the theme settings, but the text for each slide is in the home page HTML, so it's not very easy to manage.

Let's move the content for each slide (1 through 3) into their own widget blocks.

**Comment by rudy-sasquatchstudio** [comment]
updated in latest PR. I kept images in theme settings and moved the text to widget block.  Couldn't move both images and text as WYSIWYG editor would apply its own styling on initial save thought this would be too cumbersome for users to resolve
