### ISSUE TITLE
Make the home + shop items in menu hard coded

### ISSUE THREAD

**Issue by dhalarewich** [lemonstand/lscloud-theme-laboutique#24]
Currently, the shop menu, which has a drop-down list of categories is hard coded.

Let's make Home + Shop items in the menu hard coded, so that the drop-down category navigation can be dynamic. This is similar to how the Zest theme handles it.

<img width="500" alt="home___la_boutique" src="https://user-images.githubusercontent.com/1108337/27164964-b8c1333c-5145-11e7-91a3-a7a831a8397e.png">

**Comment by rudy-sasquatchstudio** [comment]
updated in latest PR
