### ISSUE TITLE
"pay now" button (last step of checkout) not working on internet explorer

### ISSUE THREAD

**Issue by kabirvirji** [lemonstand/lscloud-theme-laboutique#6]
Trying to access from null:

![image](https://cloud.githubusercontent.com/assets/11722981/17377653/77dc53ca-596f-11e6-975e-a4b6eb1b341c.png)

possible solution: (below code works, although there may be a better solution)

add `<meta http-equiv="X-UA-Compatible" content="IE=edge;chrome=1" />` to `layout-head` partial

**Comment by robotpony** [comment]
Note that you need to control the doc type as well (`<!DOCTYPE html>`), and the scripts will need to be loaded in order (jQuery before core.js).

**Comment by robotpony** [comment]
Also worth noting that there is an IE11 (and older) setting that can break JS pretty badly:
- Compatibility View Setting (Display intranet sites in Compatibility View)

This triggers a mode that turns IE into an ancient version, and is something we can't support. It's worth checking this in our tests.

**Comment by robotpony** [comment]
It's worth checking the document mode to ensure the correct IE version is being triggered by the doc type:

![IE Mode](https://f.cloud.github.com/assets/4163955/1646112/f89c4a62-5911-11e3-8d54-491234c02423.jpg)

(image borrowed from another project)

**Comment by kabirvirji** [comment]
PR: https://github.com/lemonstand/lscloud-theme-laboutique/pull/7
